// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.
// prettier-ignore
const awsmobile = {
    "aws_project_region": "ap-northeast-2",
    "aws_cognito_identity_pool_id": "ap-northeast-2:12d8496a-2cb6-43a8-b43b-9dcc3fd0b096",
    "aws_cognito_region": "ap-northeast-2",
    "aws_user_pools_id": "ap-northeast-2_7SnwnMHvg",
    "aws_user_pools_web_client_id": "3q3jtj1a4r1ja57ae9prtu1r63",
    "oauth": {
        "domain": "fpradmin-prod-auth.auth.ap-northeast-2.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "http://localhost/",
        "redirectSignOut": "http://localhost/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_cloud_logic_custom": [
        {
            "name": "fpradmin-prod-api-v1",
            "endpoint": "https://4wo4satghh.execute-api.ap-northeast-2.amazonaws.com/prod/v1",
            "region": "ap-northeast-2"
        },
        {
            "name": "fpradmin-prod-cdn-v1",
            "endpoint": "https://cdn.prmagnet.co.kr/v1",
            "region": "ap-northeast-2"
        },
        {
            "name": "fpradmin-prod-noneauth-v1",
            "endpoint": "https://4wo4satghh.execute-api.ap-northeast-2.amazonaws.com/prod/noneauth/v1",
            "region": "ap-northeast-2"
        }
    ],
    "aws_appsync_graphqlEndpoint": "https://kh7bk7qcifhmviudu43jevby4a.appsync-api.ap-northeast-2.amazonaws.com/graphql",
    "aws_appsync_region": "ap-northeast-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_user_files_s3_bucket": "fpr-prod-file",
    "aws_user_files_s3_bucket_region": "ap-northeast-2",
    "aws_content_delivery_bucket": "fpr-prod-cms",
    "aws_content_delivery_bucket_region": "ap-northeast-2",
    "aws_content_delivery_url": "fpr-prod-src"
};
export default awsmobile;
